[database]
path = "./pathway/database/IAA_database_complete.dmnd"

[criteria]
# criteria default: find highest bit-score (column: score)
# options: score, evalue, identity_percentage, query_coverage
column = "score"
filter = ["coverage=50"]

[match_enzyme]
model = "prob"

[executable]
prodigal_path = "./bin/prodigal" # download "prodigal" and put its path here
diamond_path = "./bin/diamond" # download "diamond" and put its path here
