[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["biopathpred*"]

[project]
name = "biopathpred"
version = "0.0.1"
authors = [
  { name = "Zheng-Xiang Ye", email="b07613010@ntu.edu.tw"},
  { name="Steven Wu", email="stevenwu@ntu.edu.tw" },
]
description = "TODO"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "tqdm",
  "Bio==1.7.1",
  "biopython",
  "numpy==1.23.5",
  "pandas==1.5.2",
  "pytest==7.1.2",
  "tomli==2.0.1"
]

[project.scripts]
biopathpred = "biopathpred.cli:main"
